repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: "^(01|02)_markdown_quality_assurance_.*\\.md$"
      - id: end-of-file-fixer
        exclude: "^(01|02)_markdown_quality_assurance_.*\\.md$"

  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: npx markdownlint-cli '**/*.md'
        language: node
        files: "\\.md$"
        exclude: "^(01|02)_markdown_quality_assurance_.*\\.md$"
        pass_filenames: false
      - id: textlint
        name: textlint
        entry: npx textlint '**/*.md'
        language: node
        files: "\\.md$"
        exclude: "^(01|02)_markdown_quality_assurance_.*\\.md$"
        pass_filenames: false
      - id: cspell
        name: cspell
        entry: npx cspell '**/*.md'
        language: node
        files: "\\.md$"
        exclude: "^(01|02)_markdown_quality_assurance_.*\\.md$"
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: npx prettier --check '**/*.md'
        language: node
        files: "\\.md$"
        exclude: "^(01|02)_markdown_quality_assurance_.*\\.md$"
        pass_filenames: false
